import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import Loading from "./loading"
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Suspense fallback={<Loading/>}>
          <main className="px-5">{children}</main>
        </Suspense>
      </body>
    </html>
  );
}
